//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeProvisionedService) DeepCopyInto(out *FakeProvisionedService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeProvisionedService.
func (in *FakeProvisionedService) DeepCopy() *FakeProvisionedService {
	if in == nil {
		return nil
	}
	out := new(FakeProvisionedService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeProvisionedService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedServiceSpec) DeepCopyInto(out *ProvisionedServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedServiceSpec.
func (in *ProvisionedServiceSpec) DeepCopy() *ProvisionedServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisionedServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedServiceStatus) DeepCopyInto(out *ProvisionedServiceStatus) {
	*out = *in
	out.Binding = in.Binding
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedServiceStatus.
func (in *ProvisionedServiceStatus) DeepCopy() *ProvisionedServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ProvisionedServiceStatus)
	in.DeepCopyInto(out)
	return out
}
