/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/pivotal/kpack/pkg/apis/experimental/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CustomBuilderLister helps list CustomBuilders.
type CustomBuilderLister interface {
	// List lists all CustomBuilders in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.CustomBuilder, err error)
	// CustomBuilders returns an object that can list and get CustomBuilders.
	CustomBuilders(namespace string) CustomBuilderNamespaceLister
	CustomBuilderListerExpansion
}

// customBuilderLister implements the CustomBuilderLister interface.
type customBuilderLister struct {
	indexer cache.Indexer
}

// NewCustomBuilderLister returns a new CustomBuilderLister.
func NewCustomBuilderLister(indexer cache.Indexer) CustomBuilderLister {
	return &customBuilderLister{indexer: indexer}
}

// List lists all CustomBuilders in the indexer.
func (s *customBuilderLister) List(selector labels.Selector) (ret []*v1alpha1.CustomBuilder, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CustomBuilder))
	})
	return ret, err
}

// CustomBuilders returns an object that can list and get CustomBuilders.
func (s *customBuilderLister) CustomBuilders(namespace string) CustomBuilderNamespaceLister {
	return customBuilderNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CustomBuilderNamespaceLister helps list and get CustomBuilders.
type CustomBuilderNamespaceLister interface {
	// List lists all CustomBuilders in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.CustomBuilder, err error)
	// Get retrieves the CustomBuilder from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.CustomBuilder, error)
	CustomBuilderNamespaceListerExpansion
}

// customBuilderNamespaceLister implements the CustomBuilderNamespaceLister
// interface.
type customBuilderNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CustomBuilders in the indexer for a given namespace.
func (s customBuilderNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.CustomBuilder, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.CustomBuilder))
	})
	return ret, err
}

// Get retrieves the CustomBuilder from the indexer for a given namespace and name.
func (s customBuilderNamespaceLister) Get(name string) (*v1alpha1.CustomBuilder, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("custombuilder"), name)
	}
	return obj.(*v1alpha1.CustomBuilder), nil
}
