# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/client-go/dynamic/fake",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/client-go/tools/clientcmd",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
  "github.com/buildpack/imgutil",
]

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[constraint]]
  name = "github.com/knative/build"
  version = "v0.7.0"

[[override]]
  name = "github.com/knative/pkg"
  branch = "release-0.7"

[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2019-06-04
  revision = "1c6c7f61e8a5402b606c3c6db169fdcd1b0712b7"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[override]]
  name = "github.com/json-iterator/go"
  version = "^1.1.6"
  # This is the commit at which k8s depends on this in 1.11
  # It seems to be broken at HEAD.

[[override]]
  name = "github.com/rogpeppe/go-internal"
  # HEAD as of 2019-01-09
  # Needed because release 1.0.0 does not contain a LICENSE file
  revision = "4bbc89b6501cca7dd6b5557d78d70c8d2c6e8b97"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  # Needed to downgrade protobuf to v2
  version = "v0.1.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/test-infra"
  non-go = false

[[constraint]]
  name = "github.com/sclevine/spec"
  version = "1.2.0"

[[constraint]]
  name = "github.com/buildpack/lifecycle"
  version = "0.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.12.0"

[[override]]
  name = "golang.org/x/net"
  revision = "3b0461eec859c4b73bb64fdc8285971fd33e3938"
  
[[override]]
  name = "github.com/buildpack/imgutil"
  revision = "4a2138287c60c7ef87274f5ab85caca0d11fad34"

[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  # HEAD as of 2019-02-11
  # Needed because this includes a fix to support Stackdriver built-in metrics
  revision = "c06c82c832edca4eaf7b0241bd655560a1be0346"