{{- if .Values.controllerServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kpack.controllerServiceAccountName" . }}
  labels:
    {{- include "kpack.labels" . | nindent 4 }}
  {{- with .Values.controllerServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
