{{- if .Values.createControllerRBAC -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kpack.fullname" . }}-controller-admin
  labels: {{- include "kpack.labels" . |  nindent 4 }}
rules:
- apiGroups:
  - kpack.io
  resources:
  - builds
  - builds/status
  - builds/finalizers
  - images
  - images/status
  - images/finalizers
  - builders
  - builders/status
  - clusterbuilders
  - clusterbuilders/status
  - clusterstores
  - clusterstores/status
  - clusterstacks
  - clusterstacks/status
  - sourceresolvers
  - sourceresolvers/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kpack.fullname" . }}-controller-admin-binding
  labels: {{- include "kpack.labels" . |  nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kpack.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kpack.fullname" . }}-controller-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kpack.fullname" . }}-controller-local-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kpack.labels" . |  nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kpack.fullname" . }}-controller-local-config-binding
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kpack.labels" . |  nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kpack.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kpack.fullname" . }}-controller-local-config
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}