apiVersion: v1
kind: Service
metadata:
  # These names are hardcoded and not prefixed with the release name
  # since we currently have certain webhook configs hardcoded.
  # TODO: Add a release name prefix once this https://github.com/pivotal/kpack/issues/688
  # is resolved.
  name: kpack-webhook
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "kpack.labels" . |  nindent 4 }}
spec:
  ports:
  - port: 443
    # This port is hardcoded
    # since we currently have certain webhook configs hardcoded.
    # TODO: Add a release name prefix once this https://github.com/pivotal/kpack/issues/688
    # is resolved.
    targetPort: 8443
  selector: {{- include "kpack.selectorLabels" . | nindent 4 }}
    component: webhook
