apiVersion: v1
kind: Service
metadata:
  name: {{ include "kpack.fullname" . }}-webhook
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "kpack.labels" . |  nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: {{ .Values.webhookContainerPort }}
  selector: {{- include "kpack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
