apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kpack.fullname" . }}.defaults.webhook.kpack.io
  labels: {{- include "kpack.labels" . |  nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ include "kpack.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
  failurePolicy: Fail
  sideEffects: None
  name: {{ include "kpack.fullname" . }}.defaults.webhook.kpack.io
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kpack.fullname" . }}.validation.webhook.kpack.io
  labels: {{- include "kpack.labels" . |  nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ include "kpack.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
  failurePolicy: Fail
  sideEffects: None
  name: {{ include "kpack.fullname" . }}.validation.webhook.kpack.io