// Code generated by counterfeiter. DO NOT EDIT.
package sourceresolverfakes

import (
	"sync"

	"github.com/pivotal/build-service-system/pkg/apis/build/v1alpha1"
	"github.com/pivotal/build-service-system/pkg/reconciler/v1alpha1/sourceresolver"
)

type FakeResolver struct {
	ResolveStub        func(*v1alpha1.SourceResolver) (v1alpha1.ResolvedSource, error)
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 *v1alpha1.SourceResolver
	}
	resolveReturns struct {
		result1 v1alpha1.ResolvedSource
		result2 error
	}
	resolveReturnsOnCall map[int]struct {
		result1 v1alpha1.ResolvedSource
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResolver) Resolve(arg1 *v1alpha1.SourceResolver) (v1alpha1.ResolvedSource, error) {
	fake.resolveMutex.Lock()
	ret, specificReturn := fake.resolveReturnsOnCall[len(fake.resolveArgsForCall)]
	fake.resolveArgsForCall = append(fake.resolveArgsForCall, struct {
		arg1 *v1alpha1.SourceResolver
	}{arg1})
	fake.recordInvocation("Resolve", []interface{}{arg1})
	fake.resolveMutex.Unlock()
	if fake.ResolveStub != nil {
		return fake.ResolveStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.resolveReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResolver) ResolveCallCount() int {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	return len(fake.resolveArgsForCall)
}

func (fake *FakeResolver) ResolveCalls(stub func(*v1alpha1.SourceResolver) (v1alpha1.ResolvedSource, error)) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = stub
}

func (fake *FakeResolver) ResolveArgsForCall(i int) *v1alpha1.SourceResolver {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	argsForCall := fake.resolveArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeResolver) ResolveReturns(result1 v1alpha1.ResolvedSource, result2 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	fake.resolveReturns = struct {
		result1 v1alpha1.ResolvedSource
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) ResolveReturnsOnCall(i int, result1 v1alpha1.ResolvedSource, result2 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	if fake.resolveReturnsOnCall == nil {
		fake.resolveReturnsOnCall = make(map[int]struct {
			result1 v1alpha1.ResolvedSource
			result2 error
		})
	}
	fake.resolveReturnsOnCall[i] = struct {
		result1 v1alpha1.ResolvedSource
		result2 error
	}{result1, result2}
}

func (fake *FakeResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sourceresolver.Resolver = new(FakeResolver)
