apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: ClusterStore
metadata:
  name: sample-cluster-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/adopt-openjdk
  - image: gcr.io/paketo-buildpacks/gradle
  - image: gcr.io/paketo-buildpacks/maven
  - image: gcr.io/paketo-buildpacks/executable-jar
  - image: gcr.io/paketo-buildpacks/apache-tomcat
  - image: gcr.io/paketo-buildpacks/spring-boot
  - image: gcr.io/paketo-buildpacks/dist-zip
