/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/pivotal/kpack/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// CustomBuilders returns a CustomBuilderInformer.
	CustomBuilders() CustomBuilderInformer
	// CustomClusterBuilders returns a CustomClusterBuilderInformer.
	CustomClusterBuilders() CustomClusterBuilderInformer
	// Stacks returns a StackInformer.
	Stacks() StackInformer
	// Stores returns a StoreInformer.
	Stores() StoreInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// CustomBuilders returns a CustomBuilderInformer.
func (v *version) CustomBuilders() CustomBuilderInformer {
	return &customBuilderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CustomClusterBuilders returns a CustomClusterBuilderInformer.
func (v *version) CustomClusterBuilders() CustomClusterBuilderInformer {
	return &customClusterBuilderInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Stacks returns a StackInformer.
func (v *version) Stacks() StackInformer {
	return &stackInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Stores returns a StoreInformer.
func (v *version) Stores() StoreInformer {
	return &storeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
