// Code generated by counterfeiter. DO NOT EDIT.
package clusterstorefakes

import (
	"sync"

	buildapi "github.com/pivotal/kpack/pkg/apis/build/v1alpha1"
	"github.com/pivotal/kpack/pkg/reconciler/clusterstore"
)

type FakeStoreReader struct {
	ReadStub        func([]buildapi.StoreImage) ([]buildapi.StoreBuildpack, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 []buildapi.StoreImage
	}
	readReturns struct {
		result1 []buildapi.StoreBuildpack
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 []buildapi.StoreBuildpack
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStoreReader) Read(arg1 []buildapi.StoreImage) ([]buildapi.StoreBuildpack, error) {
	var arg1Copy []buildapi.StoreImage
	if arg1 != nil {
		arg1Copy = make([]buildapi.StoreImage, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		arg1 []buildapi.StoreImage
	}{arg1Copy})
	fake.recordInvocation("Read", []interface{}{arg1Copy})
	fake.readMutex.Unlock()
	if fake.ReadStub != nil {
		return fake.ReadStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.readReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStoreReader) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeStoreReader) ReadCalls(stub func([]buildapi.StoreImage) ([]buildapi.StoreBuildpack, error)) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *FakeStoreReader) ReadArgsForCall(i int) []buildapi.StoreImage {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	argsForCall := fake.readArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStoreReader) ReadReturns(result1 []buildapi.StoreBuildpack, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 []buildapi.StoreBuildpack
		result2 error
	}{result1, result2}
}

func (fake *FakeStoreReader) ReadReturnsOnCall(i int, result1 []buildapi.StoreBuildpack, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 []buildapi.StoreBuildpack
			result2 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 []buildapi.StoreBuildpack
		result2 error
	}{result1, result2}
}

func (fake *FakeStoreReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStoreReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ clusterstore.StoreReader = new(FakeStoreReader)
