apiVersion: build.pivotal.io/v1alpha1
kind: Build
metadata:
  name: sample
spec:
  tags:
  - sample/image
  serviceAccount: serviceaccount
  builder:
    image: gcr.io/paketo-buildpacks/builder:base
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: master