apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: default
spec:
  id: "io.buildpacks.stacks.bionic"
  serviceAccountRef:
    name: default
    namespace: default
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
