apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: sample-cluster-store
spec:
  serviceAccountRef:
    name: default
    namespace: default
  sources:
  - image: paketobuildpacks/java
  - image: paketobuildpacks/nodejs
