apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: default
spec:
  id: "io.buildpacks.stacks.jammy"
  serviceAccountRef:
    name: default
    namespace: default
  buildImage:
    image: "paketobuildpacks/build-jammy-base"
  runImage:
    image: "paketobuildpacks/run-jammy-base"
