apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: sample-cluster-store
spec:
  serviceAccountRef:
    name: default
    namespace: default
  sources:
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
