apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample
spec:
  builderRef: sample-builder
  tag: registry.default.svc.cluster.local:5000/sample/image
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: master