apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: sample-binding
spec:
  tag: sample/image-with-binding
  builder:
    kind: Builder
    name: sample-builder
  serviceAccount: service-account
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: 0eccc6c2f01d9f055087ebbf03526ed0623e014a
  build:
    bindings:
    - name: sample
      metadataRef:
        name: sample-binding-metadata
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: sample-binding-with-secret
spec:
  tag: sample/image-with-binding-secret
  builder:
    kind: Builder
    name: sample-builder
  serviceAccount: service-account
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: 0eccc6c2f01d9f055087ebbf03526ed0623e014a
  build:
    bindings:
    - name: sample
      metadataRef:
        name: sample-binding-metadata
      secretRef:
        name: sample-binding-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-binding-metadata
data:
  kind: mysql
  provider: sample
  tags: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-binding-secret
type: Opaque
stringData:
  hostname: localhost
  jdbcUrl: jdbc:mysql://localhost:3306/default?user=root&password=
  name: default
  password: ""
  port: "3306"
  uri: mysql://root:@localhost:3306/default?reconnect=true
  username: root
