apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: sample
spec:
  tag: sample/image-from-jar
  builder:
    kind: ClusterBuilder
    name: cluster-sample-builder
  serviceAccount: service-account
  source:
    blob:
      url: https://storage.googleapis.com/build-service/sample-apps/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar
