apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: sample-with-volume-cache
spec:
  tag: sample/image-from-git
  builder:
    kind: ClusterBuilder
    name: cluster-sample-builder
  serviceAccountName: service-account
  cache:
    volume:
      request: 1G
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: master
---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: sample-with-volume-cache
spec:
  tag: sample/image-from-git
  builder:
    kind: ClusterBuilder
    name: cluster-sample-builder
  serviceAccountName: service-account
  cache:
    registry:
      tag: sample/image-from-git-cache
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: master
