apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: sample-binding
spec:
  tag: sample/image-with-binding
  builder:
    kind: Builder
    name: sample-builder
  serviceAccountName: service-account
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: 0eccc6c2f01d9f055087ebbf03526ed0623e014a
  build:
    services:
      - name: sample-binding-secret
        kind: Secret
        apiVersion: v1
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-binding-secret
type: Opaque
stringData:
  type: mysql
  provider: sample
  hostname: localhost
  jdbcUrl: jdbc:mysql://localhost:3306/default?user=root&password=
  name: default
  password: ""
  port: "3306"
  uri: mysql://root:@localhost:3306/default?reconnect=true
  username: root
