apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builders.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Builder
    singular: builder
    plural: builders
    shortNames:
    - cnbbuilder
    - cnbbuilders
    - bldr
  scope: Namespaced
  subresources:
    status: {}
