apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buildpacks.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
  names:
    kind: Buildpack
    listKind: BuildpackList
    singular: buildpack
    plural: buildpacks
    shortNames:
    - bp
    - bps
    categories:
    - kpack
  scope: Namespaced

