apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: extensions.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
  names:
    kind: Extension
    listKind: ExtensionList
    singular: extension
    plural: extensions
    shortNames:
    - ext
    - exts
    categories:
    - kpack
  scope: Namespaced

