#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
kpack_version: dev
controller:
  image: controller
webhook:
  image: webhook
build_init:
  image: build-init
build_waiter:
  image: build-waiter
rebase:
  image: rebase
completion:
  image: completion
lifecycle:
  image: buildpacksio/lifecycle
