// Code generated by counterfeiter. DO NOT EDIT.
package stackfakes

import (
	"sync"

	"github.com/pivotal/kpack/pkg/apis/experimental/v1alpha1"
	"github.com/pivotal/kpack/pkg/reconciler/v1alpha1/stack"
)

type FakeStackReader struct {
	ReadStub        func(v1alpha1.StackSpec) (v1alpha1.ResolvedStack, error)
	readMutex       sync.RWMutex
	readArgsForCall []struct {
		arg1 v1alpha1.StackSpec
	}
	readReturns struct {
		result1 v1alpha1.ResolvedStack
		result2 error
	}
	readReturnsOnCall map[int]struct {
		result1 v1alpha1.ResolvedStack
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStackReader) Read(arg1 v1alpha1.StackSpec) (v1alpha1.ResolvedStack, error) {
	fake.readMutex.Lock()
	ret, specificReturn := fake.readReturnsOnCall[len(fake.readArgsForCall)]
	fake.readArgsForCall = append(fake.readArgsForCall, struct {
		arg1 v1alpha1.StackSpec
	}{arg1})
	fake.recordInvocation("Read", []interface{}{arg1})
	fake.readMutex.Unlock()
	if fake.ReadStub != nil {
		return fake.ReadStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.readReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStackReader) ReadCallCount() int {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	return len(fake.readArgsForCall)
}

func (fake *FakeStackReader) ReadCalls(stub func(v1alpha1.StackSpec) (v1alpha1.ResolvedStack, error)) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = stub
}

func (fake *FakeStackReader) ReadArgsForCall(i int) v1alpha1.StackSpec {
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	argsForCall := fake.readArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStackReader) ReadReturns(result1 v1alpha1.ResolvedStack, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	fake.readReturns = struct {
		result1 v1alpha1.ResolvedStack
		result2 error
	}{result1, result2}
}

func (fake *FakeStackReader) ReadReturnsOnCall(i int, result1 v1alpha1.ResolvedStack, result2 error) {
	fake.readMutex.Lock()
	defer fake.readMutex.Unlock()
	fake.ReadStub = nil
	if fake.readReturnsOnCall == nil {
		fake.readReturnsOnCall = make(map[int]struct {
			result1 v1alpha1.ResolvedStack
			result2 error
		})
	}
	fake.readReturnsOnCall[i] = struct {
		result1 v1alpha1.ResolvedStack
		result2 error
	}{result1, result2}
}

func (fake *FakeStackReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readMutex.RLock()
	defer fake.readMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStackReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ stack.StackReader = new(FakeStackReader)
