apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builders.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: ".status.latestImage"
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
  names:
    kind: Builder
    singular: builder
    plural: builders
    shortNames:
    - bldr
    - bldrs
    categories:
    - kpack
  scope: Namespaced
