name: 'Pack Build'
description: 'Pack build kpack images'

inputs:
  tag:
    description: 'location to write image'
    required: true
  bp_go_targets:
    description: 'value of BP_GO_TARGETS env'
  builder:
    description: 'builder image'
    required: true
    default: 'paketobuildpacks/builder-jammy-tiny'
  pack_version:
    description: 'version of pack to use'
    required: true
  additional_pack_args:
    description: 'additional args for pack'
  artifact_name:
    description: 'name of the artifact to upload'
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version-file: 'go.mod'
  - name: setup-pack
    uses: buildpacks/github-actions/setup-pack@v5.0.0
    with:
      pack-version: ${{ inputs.pack_version }}
  - name: build
    shell: bash
    run: |
      [[ $GITHUB_REF =~ ^refs\/tags\/v(.*)$ ]] && version=${BASH_REMATCH[1]} || version=0.0.0

      KPACK_VERSION=$version
      KPACK_COMMIT=$GITHUB_SHA
      mkdir report

      export PATH="$PATH:$(pwd)"
      pack build ${{ inputs.tag }} \
        --builder ${{ inputs.builder }} \
        --env BP_GO_LDFLAGS="-X 'github.com/pivotal/kpack/cmd.Version=${KPACK_VERSION}' -X 'github.com/pivotal/kpack/cmd.Commit=${KPACK_COMMIT}'" \
        --env BP_GO_TARGETS="${{ inputs.bp_go_targets }}" \
        --report-output-dir . \
        --cache-image ${{ inputs.tag }}-cache \
        --publish ${{ inputs.additional_pack_args }}

      mkdir images
      digest=$(go run .github/actions/pack-build/report.go -path ./report.toml)
      name=$(basename ${{ inputs.tag }})
      echo "${{ inputs.tag }}@${digest}" > images/$name
      cat images/$name
  - name: Upload Image Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.artifact_name }}
      path: images/
